WORK_BASENAME = Star-Trek--We-the-Living-Dead
DOCS_BASE = $(WORK_BASENAME) $(WORK_BASENAME)-hebrew

SELINA_UPLOAD_TEMP_DEST = temp-star-trek-we-the-living-dead-P9n7ybv3wq2t

include $(SDIR)/screenplays_common.mak

